In [1]:

from positionsplanung.bauteile.stahlbetonstuetze import Stahlbetonstuetze, CheckResult



stuetze = Stahlbetonstuetze(
    b_mm=200,
    h_mm=300,
    l_mm=3200,
    as_vorh_cm2=8.50,
)

stuetze.kennwerte_df

                Kennwert    Wert Einheit
0               Breite b   200.0      mm
1                 Höhe h   300.0      mm
2                Länge l  3200.0      mm
3   Querschnittsfläche A   600.0     cm²
4     Kleinste Abmessung   200.0      mm
5       Seitenverhältnis     1.5       -
6  Schlankheitsindikator    16.0       -
7                 As,min     1.2     cm²
8                 As,max    24.0     cm²
9                As,vorh     8.5     cm²

In [2]:
stuetze.checks_df

,Check,Status,Wert,Grenzwert,Einheit,Meldung
0,Mindestabmessung,OK,200.0,200.0,mm,Kleinste Abmessung 200 mm ≥ 200 mm.
1,"Mindestbewehrung As,min",OK,8.5,1.2,cm²,"As,vorh = 8.50 cm² ≥ As,min = 1.20 cm²."
2,"Maximalbewehrung As,max",OK,8.5,24.0,cm²,"As,vorh = 8.50 cm² ≤ As,max = 24.00 cm²."

In [3]:
stuetze.checks_df[["Check", "Status", "Meldung"]]

                     Check Status                                   Meldung
0         Mindestabmessung     OK       Kleinste Abmessung 200 mm ≥ 200 mm.
1  Mindestbewehrung As,min     OK   As,vorh = 8.50 cm² ≥ As,min = 1.20 cm².
2  Maximalbewehrung As,max     OK  As,vorh = 8.50 cm² ≤ As,max = 24.00 cm².

In [4]:
from IPython.display import Markdown, display

md = stuetze.steckbrief_markdown()
display(Markdown(md))

# Bauteil-Steckbrief

## Bauteilangaben

- Breite b = 200 mm
- Höhe h = 300 mm
- Länge l = 3200 mm

## Kennwerte

| Kennwert              |   Wert | Einheit   |
|:----------------------|-------:|:----------|
| Breite b              |  200   | mm        |
| Höhe h                |  300   | mm        |
| Länge l               | 3200   | mm        |
| Querschnittsfläche A  |  600   | cm²       |
| Kleinste Abmessung    |  200   | mm        |
| Seitenverhältnis      |    1.5 | -         |
| Schlankheitsindikator |   16   | -         |
| As,min                |    1.2 | cm²       |
| As,max                |   24   | cm²       |
| As,vorh               |    8.5 | cm²       |

## Prüfungen

| Check                   | Status   |   Wert |   Grenzwert | Einheit   | Meldung                                  |
|:------------------------|:---------|-------:|------------:|:----------|:-----------------------------------------|
| Mindestabmessung        | OK       |  200   |       200   | mm        | Kleinste Abmessung 200 mm ≥ 200 mm.      |
| Mindestbewehrung As,min | OK       |    8.5 |         1.2 | cm²       | As,vorh = 8.50 cm² ≥ As,min = 1.20 cm².  |
| Maximalbewehrung As,max | OK       |    8.5 |        24   | cm²       | As,vorh = 8.50 cm² ≤ As,max = 24.00 cm². |

## Fazit

Alle geprüften Kriterien sind erfüllt.

In [5]:
from pathlib import Path

Path("steckbrief.qmd").write_text(md, encoding="utf-8")

1327

In [6]:
from positionsplanung.rechteckquerschnitt import Rechteckquerschnitt

In [8]:
rq1 = Rechteckquerschnitt(b_mm=200, h_mm=300)
rq1.to_dict()

{'b_mm': 200.0,
 'h_mm': 300.0,
 'querschnittsflaeche_cm2': 60000.0,
 'kleinste_abmessung_cm': 200.0,
 'groesste_abmessung_cm': 300.0,
 'seitenverhaeltnis': 1.5,
 'umfang_cm': 1000.0,
 'diagonal_cm': 360.5551275463989,
 'traegheitsmoment_y_cm4': 450000000.0,
 'traegheitsmoment_z_cm4': 200000000.0,
 'widerstandsmoment_y_cm3': 3000.0,
 'widerstandsmoment_z_cm3': 2000.0,
 'traegheitsradius_y_cm': 86.60254037844386,
 'traegheitsradius_z_cm': 57.735026918962575,
 'traegheitsradius_min_cm': 57.735026918962575}